# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LastPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyMuiscLIstWindow(object):
    def setupUi(self, MyMuiscLIstWindow):
        MyMuiscLIstWindow.setObjectName("MyMuiscLIstWindow")
        MyMuiscLIstWindow.resize(800, 600)
        MyMuiscLIstWindow.setStyleSheet("background-color: #CCFF00;")
        self.centralwidget = QtWidgets.QWidget(MyMuiscLIstWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollAreaFor_music2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaFor_music2.setGeometry(QtCore.QRect(19, 86, 761, 391))
        self.scrollAreaFor_music2.setStyleSheet("background-color: white")
        self.scrollAreaFor_music2.setWidgetResizable(True)
        self.scrollAreaFor_music2.setObjectName("scrollAreaFor_music2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaFor_music2.setWidget(self.scrollAreaWidgetContents)
        self.DecorText_label = QtWidgets.QLabel(self.centralwidget)
        self.DecorText_label.setGeometry(QtCore.QRect(320, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DecorText_label.setFont(font)
        self.DecorText_label.setStyleSheet("background-color: white")
        self.DecorText_label.setObjectName("DecorText_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 490, 761, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Remove_button2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Remove_button2.setFont(font)
        self.Remove_button2.setStyleSheet("background-color: white")
        self.Remove_button2.setObjectName("Remove_button2")
        self.horizontalLayout.addWidget(self.Remove_button2)
        self.See_info_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.See_info_button.setFont(font)
        self.See_info_button.setStyleSheet("background-color: white")
        self.See_info_button.setObjectName("See_info_button")
        self.horizontalLayout.addWidget(self.See_info_button)
        self.Quit_button2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Quit_button2.setFont(font)
        self.Quit_button2.setStyleSheet("background-color: white")
        self.Quit_button2.setObjectName("Quit_button2")
        self.horizontalLayout.addWidget(self.Quit_button2)
        self.genre_comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.genre_comboBox2.setGeometry(QtCore.QRect(630, 50, 151, 22))
        self.genre_comboBox2.setStyleSheet("background-color: white")
        self.genre_comboBox2.setObjectName("genre_comboBox2")
        self.Search_lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Search_lineEdit2.setGeometry(QtCore.QRect(20, 50, 451, 22))
        self.Search_lineEdit2.setStyleSheet("background-color: white")
        self.Search_lineEdit2.setObjectName("Search_lineEdit2")
        self.Year_combobox2 = QtWidgets.QComboBox(self.centralwidget)
        self.Year_combobox2.setGeometry(QtCore.QRect(500, 50, 111, 22))
        self.Year_combobox2.setStyleSheet("background-color: white")
        self.Year_combobox2.setObjectName("Year_combobox2")
        MyMuiscLIstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyMuiscLIstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MyMuiscLIstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyMuiscLIstWindow)
        self.statusbar.setObjectName("statusbar")
        MyMuiscLIstWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MyMuiscLIstWindow)
        QtCore.QMetaObject.connectSlotsByName(MyMuiscLIstWindow)

    def retranslateUi(self, MyMuiscLIstWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMuiscLIstWindow.setWindowTitle(_translate("MyMuiscLIstWindow", "MainWindow"))
        self.DecorText_label.setText(_translate("MyMuiscLIstWindow", "Your List"))
        self.Remove_button2.setText(_translate("MyMuiscLIstWindow", "Remove from the list"))
        self.See_info_button.setText(_translate("MyMuiscLIstWindow", "See the information"))
        self.Quit_button2.setText(_translate("MyMuiscLIstWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyMuiscLIstWindow = QtWidgets.QMainWindow()
    ui = Ui_MyMuiscLIstWindow()
    ui.setupUi(MyMuiscLIstWindow)
    MyMuiscLIstWindow.show()
    sys.exit(app.exec_())
