# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photo1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Username_editline = QtWidgets.QLineEdit(self.centralwidget)
        self.Username_editline.setGeometry(QtCore.QRect(200, 200, 400, 40))
        self.Username_editline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Username_editline.setObjectName("Username_editline")
        self.Password_editline = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_editline.setGeometry(QtCore.QRect(200, 270, 400, 40))
        self.Password_editline.setObjectName("Password_editline")
        self.LogIn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.LogIn_btn.setGeometry(QtCore.QRect(200, 360, 400, 40))
        self.LogIn_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.LogIn_btn.setSizeIncrement(QtCore.QSize(0, 0))
        self.LogIn_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 220);  /* თითქმის სრული შავი */\n"
"    color: #ffffff;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 30, 30, 220);  /* ღია შავი hover */\n"
"}")
        self.LogIn_btn.setObjectName("LogIn_btn")
        self.Register_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Register_btn.setGeometry(QtCore.QRect(200, 430, 400, 40))
        self.Register_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.Register_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 220);  /* თითქმის სრული შავი */\n"
"    color: #ffffff;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 30, 30, 220);  /* ღია შავი hover */\n"
"}")
        self.Register_btn.setObjectName("Register_btn")
        self.Quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_btn.setGeometry(QtCore.QRect(200, 500, 400, 40))
        self.Quit_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.Quit_btn.setSizeIncrement(QtCore.QSize(0, 0))
        self.Quit_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 220);  /* თითქმის სრული შავი */\n"
"    color: #ffffff;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 30, 30, 220);  /* ღია შავი hover */\n"
"}")
        self.Quit_btn.setObjectName("Quit_btn")
        self.WELCOME_TEXT = QtWidgets.QLabel(self.centralwidget)
        self.WELCOME_TEXT.setGeometry(QtCore.QRect(285, 80, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.WELCOME_TEXT.setFont(font)
        self.WELCOME_TEXT.setMouseTracking(False)
        self.WELCOME_TEXT.setObjectName("WELCOME_TEXT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Username_editline.setText(_translate("MainWindow", "Username"))
        self.Password_editline.setText(_translate("MainWindow", "Password"))
        self.LogIn_btn.setText(_translate("MainWindow", "Log In"))
        self.Register_btn.setText(_translate("MainWindow", "Register"))
        self.Quit_btn.setText(_translate("MainWindow", "Quit"))
        self.WELCOME_TEXT.setText(_translate("MainWindow", "WELCOME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
