# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicSelectingWindow(object):
    def setupUi(self, MusicSelectingWindow):
        MusicSelectingWindow.setObjectName("MusicSelectingWindow")
        MusicSelectingWindow.resize(800, 600)
        MusicSelectingWindow.setStyleSheet("background-color: #CCFF00;")
        self.centralwidget = QtWidgets.QWidget(MusicSelectingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 40, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Genre_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Genre_comboBox.setStyleSheet("background-color: white")
        self.Genre_comboBox.setObjectName("Genre_comboBox")
        self.horizontalLayout.addWidget(self.Genre_comboBox)
        self.Year_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Year_comboBox.setStyleSheet("background-color: white")
        self.Year_comboBox.setObjectName("Year_comboBox")
        self.horizontalLayout.addWidget(self.Year_comboBox)
        self.Rating_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Rating_comboBox.setStyleSheet("background-color: white")
        self.Rating_comboBox.setObjectName("Rating_comboBox")
        self.horizontalLayout.addWidget(self.Rating_comboBox)
        self.scrollArea_for_music = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_for_music.setGeometry(QtCore.QRect(10, 80, 781, 401))
        self.scrollArea_for_music.setStyleSheet("background-color: white")
        self.scrollArea_for_music.setWidgetResizable(True)
        self.scrollArea_for_music.setObjectName("scrollArea_for_music")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_for_music.setWidget(self.scrollAreaWidgetContents)
        self.Search_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Search_LineEdit.setGeometry(QtCore.QRect(10, 50, 281, 22))
        self.Search_LineEdit.setStyleSheet("background-color: white")
        self.Search_LineEdit.setObjectName("Search_LineEdit")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 490, 781, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Remove1_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Remove1_Button.setStyleSheet("background-color: white")
        self.Remove1_Button.setObjectName("Remove1_Button")
        self.horizontalLayout_2.addWidget(self.Remove1_Button)
        self.Add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Add_button.setStyleSheet("background-color: white")
        self.Add_button.setObjectName("Add_button")
        self.horizontalLayout_2.addWidget(self.Add_button)
        self.SeeList_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.SeeList_Button.setStyleSheet("background-color: white")
        self.SeeList_Button.setObjectName("SeeList_Button")
        self.horizontalLayout_2.addWidget(self.SeeList_Button)
        self.Quit2_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Quit2_Button.setStyleSheet("background-color: white")
        self.Quit2_Button.setObjectName("Quit2_Button")
        self.horizontalLayout_2.addWidget(self.Quit2_Button)
        self.Decor_text_label = QtWidgets.QLabel(self.centralwidget)
        self.Decor_text_label.setGeometry(QtCore.QRect(70, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Decor_text_label.setFont(font)
        self.Decor_text_label.setObjectName("Decor_text_label")
        MusicSelectingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MusicSelectingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MusicSelectingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MusicSelectingWindow)
        self.statusbar.setObjectName("statusbar")
        MusicSelectingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MusicSelectingWindow)
        QtCore.QMetaObject.connectSlotsByName(MusicSelectingWindow)

    def retranslateUi(self, MusicSelectingWindow):
        _translate = QtCore.QCoreApplication.translate
        MusicSelectingWindow.setWindowTitle(_translate("MusicSelectingWindow", "MainWindow"))
        self.Remove1_Button.setText(_translate("MusicSelectingWindow", "Remove from the list"))
        self.Add_button.setText(_translate("MusicSelectingWindow", "Add to the list"))
        self.SeeList_Button.setText(_translate("MusicSelectingWindow", "See my list"))
        self.Quit2_Button.setText(_translate("MusicSelectingWindow", "Quit"))
        self.Decor_text_label.setText(_translate("MusicSelectingWindow", "Music List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MusicSelectingWindow = QtWidgets.QMainWindow()
    ui = Ui_MusicSelectingWindow()
    ui.setupUi(MusicSelectingWindow)
    MusicSelectingWindow.show()
    sys.exit(app.exec_())
